In [19]:
import numpy as np

# Read the input to list of boards and numbers
with open('input.txt') as f:
    lines = f.read().splitlines()  # read lines without /n

# Create a list of lines
list_of_lines = []

for line in lines:
    points = line.split(' -> ')
    points = [point.split(',') for point in points]
    points = [[int(point[0]), int(point[1])] for point in points]
    list_of_lines.append(points)

ary_of_lines = np.array(list_of_lines, dtype=int)

In [20]:
## Part 1: Count number of overlapping lines

vent_map = np.zeros((np.amax(ary_of_lines)+1, np.amax(ary_of_lines)+1))

for line in list_of_lines:
    x1, x2 = line[0][0], line[1][0]
    y1, y2 = line[0][1], line[1][1]
    if x1 == x2 or y1 == y2:
        for x in range(min([x1,x2]), max([x1,x2])+1):
            for y in range(min([y1,y2]), max([y1,y2])+1):
                vent_map[x,y] += 1
    else: 
        pass
print('solution: ', sum(sum(x > 1 for x in vent_map)))

solution:  7380


In [21]:
## Part 2: Count number of overlapping lines, including diagonals

vent_map = np.zeros((np.amax(ary_of_lines)+1, np.amax(ary_of_lines)+1))

for line in list_of_lines:
    x1, x2 = line[0][0], line[1][0]
    y1, y2 = line[0][1], line[1][1]
    if x1 == x2 or y1 == y2:
        for x in range(min([x1,x2]), max([x1,x2])+1):
            for y in range(min([y1,y2]), max([y1,y2])+1):
                vent_map[x,y] += 1
    else: 
        if x1 > x2:
            x_range = range(x1, x2-1, -1)
        else:
            x_range = range(x1, x2+1, 1)
        if y1 > y2:
            y_range = range(y1, y2-1, -1)
        else:
            y_range = range(y1, y2+1, 1)
        for x, y in zip(x_range, y_range):
            vent_map[x,y] += 1

print('solution: ', sum(sum(x > 1 for x in vent_map)))
print(vent_map)

solution:  21373
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
